trigger:
  branches:
    include:
    - "*"

pool:
  vmImage: ubuntu-latest

# Replace CONTAINER_REPOSITORY and IMAGE_TAG with your own values
variables:
- group: cs-falcon-variables
- name: CONTAINER_REPOSITORY
  value: '<repo_name>'
- name: IMAGE_TAG
  value: $(Build.BuildId)

steps:
- task: Docker@2
  displayName: 'Build container image'
  inputs:
    Dockerfile: '**/Dockerfile'
    command: 'build'
    repository: '$(CONTAINER_REPOSITORY)'
    tags: '$(IMAGE_TAG)'

- script: |
    export FALCON_CLIENT_SECRET=$(FALCON_CLIENT_SECRET)
    export FALCON_CLIENT_ID=$(FALCON_CLIENT_ID)
    export FALCON_CLOUD_REGION=$(FALCON_CLOUD_REGION)

    pip3 install docker crowdstrike-falconpy
    
    if [ ! -d container-image-scan ] ; then
      git clone https://github.com/crowdstrike/container-image-scan
    fi
    
    python3 container-image-scan/cs_scanimage.py -r $(CONTAINER_REPOSITORY) -t $(IMAGE_TAG)
  displayName: 'Scan container-image'
  
- task: Docker@2
  displayName: 'Push container image'
  inputs:
    containerRegistry: 'DockerHub'
    command: 'push'
    repository: $(CONTAINER_REPOSITORY)
    tags: $(IMAGE_TAG)
