version: 0.2

env:
  secrets-manager:
    FALCON_CLOUD: "/CodeBuild/falcon_cloud"
    FALCON_CLIENT_ID: "/CodeBuild/falcon_client_id"
    FALCON_CLIENT_SECRET: "/CodeBuild/falcon_client_secret"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - wget https://raw.githubusercontent.com/CrowdStrike/container-image-scan/main/cs_scanimage.py
      - python3 -m pip install docker-py crowdstrike-falconpy
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "Testing image with API"
      - python3 cs_scanimage.py -r $IMAGE_REPO_NAME -t $IMAGE_TAG -c $FALCON_CLOUD -s $SCORE_THRESHOLD
  post_build:
    commands:
      - echo "tagging for repo $IMAGE_REPO_NAME:$IMAGE_TAG"
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Build completed on `date`







